# Generated by Django 5.2.3 on 2025-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('password2', models.CharField(max_length=8)),
                ('scientific_degree', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
