# Generated by Django 5.2.3 on 2025-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='author',
            field=models.CharField(verbose_name=50),
        ),
    ]
