# Generated by Django 5.2.3 on 2025-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0002_alter_maqola_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
