# Generated by Django 5.2.3 on 2025-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0003_alter_maqola_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
